title: Vom Antlitz Zur Maske

title_de: Vom Antlitz Zur Maske

date: 1999

material: 

size: 

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++



Wien, Weimar, Buchenwald 1939 and
Gezeichneter Ort, Goetheblick auf Weimar und Buchenwald.

One Project, two exhibitions "From Countenance to Mask" and "A drawn place" both have exchanged locations: Goethe's Drawings and valuables of Classical Weimar were exhibited in the Buchenwald Memorial, Wax masks of concentration camp inmates were shown in Schiller Museum in Weimar. A Curatorial cooperation between Dani Karavan, Konrad Scheurmann and Naomi Tereza Salmon 

 

The Exhibition double Catalogue is available: Vom Antlitz zur Maske. Wien - Weimar - Buchenwald. Gezeichneter Ort. Goetheblicke auf Weimar und Thüringen. Edited by Volkhard Knigge and Jürgen Seifert. Gestaltung: Hinz & Kunst; Weimar, 1999; ISBN: 3-935598-00-9 


+++
