title: "Time + Space = Place"

title_de: "Zeit + Raum = Ort"

date: 2002

material: Photography, Sound, Text, Videoloop

size: 

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++

"Time + Space = Place" 

„...Space seems to be either more tamed or more harmless than time: one meets everywhere people with watches, and very seldom people who have binnacles. One must always know what time it is, (and who can calculate it from the position of the sun anymore?), yet one never asks oneself where one is, one believes one knows it: One is at home, one is in one’s office, one is in the Metro, one is in the street. That is naturally evident – but what isn’t evident? One should ask oneself from time to time where one is: make an interim balance: not only about his state of mind, his health, his ambitions, his belief and his right of existence, but above all about the topographical position, and not only in view of a place or a person one thinks about, or starts, in this sense, to think about.	(Georges Perec, Espèces d'espaces, Paris, Galilée 1974)  

I am on the roof, on the balcony, in the study. 
I’m in this town, in the other one, or oversees. 
I hear church bells, a door is slammed, dogs bark. A bicycle bell is ringing, a kid screams: „Quiet!“, 
Ravens. An airplane, muezzins, a shot, a telephone rings. 
More bells, traffic, a bomb –	(nts) 


- 2014 ASDR Nomadenetappe - Kunst und Theorie, Linz, Austria

- 2005 To Hear Is To See / Hören Ist Sehen
YYZ Artists’ Outlet, Toronto, Canada

- 2003 To Hear Is To See / Hören Ist Sehen
Klangturm St. Pölten, Austria

- 2002 To Hear Is To See/ Hören Ist Sehen
Kammgarn-Forum Vebikus, Schaffhausen, Switzerland

coll.
"TO HEAR IS TO SEE - Art in Electronic Space, for Example Radio Art and Sound Sculpture" is a project which started in 1995 by Gao Schmidt, Vienna. 




Naomi Tereza Salmon - "To Hear Is To See" Audio Sequence:

http://naomiterezasalmon.net/projects/6-to_hear_is_to_see/to_hear_is_to_see.mp3

nomadenetappe.net
http://kerneloperations.com

text_de:
+++
