title: "Evergreen"

title_de: "Evergreen"

date: 1998

material: ?

size: 1 x 1 cm

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++


This work is part of the project „Weimar - Jerusalem – Jerusalem - Weimar“. Both cities are mythical and transfigured – both embody historical, political, and ethnic new awakening, both stand for broken promises and dissapointed hope, both create a point of reference for yearnings and projections. 
Between those two cities, two histories, me – a topographical, social cultural, traveler. Between the myths and the real stories, thier images.mNo synthesis, but movements, confrontation, synergy, difference, comparisons, Import & Export: stories, mentalities, longings, flora, fauna, weather. Custom, love, hate. Past, memory, nostalgia. Tradition, language, place of residence, homeland. 

Evergreen is a modular installation of Aluminium plates on wooden blocks, set in fixed distance from each other and is brought on to the floor. The surface seems to float, the construction is invisible. The exhibition space gives the work it’s form. 

text_de:
+++
