title: "GDR Bags 1:1"

title_de: "DDR Beutel 1:1"

date: 1998

material: Original Shopping bags / 1:1 Photographs

size: each Photo 50 x 60 cm

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++


- Cloth bag*
- Shift bag
- Saxon case 

Flowered bags were the Cindarellas of everyday culture in former East Germany. Containers for scarce commodities, coverings for daily necessities. Nobody knows where they came from. Nobody looked at them. The most mundane item does not warrant a second glance. Now, having become obsolete, they are themselves rare items - vestiges of everyday poetry, a reflection of a past norm, nostalgic vehicles for memory, brightly textured fabric. 

*a brightly colored cloth shopping bag, found and bought in Thuringia after the reunification of Germany, Photos scale 1:1 Supply: endless. 

text_de:
+++
