title: Divide & Rule

title_de: Teile & Hersche

date: 2010

material: Intervention

size: Wriststrips

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++
The intervention takes place in the entrance to the venue, at the opening, where visitors and guests get a ticket, or any entrance control point. Those in charge of the entrance provide the guests with a paper made wristband, such as the ones you get when going to a concert, and are encouraged to wear it. There are three colors, and so the Multitude in this venue will be divided into three groups: 1.Group A, with a majority 2.Group B with a minority (band in that color will be produced in alesser amount) and 3. Staff. All are told when and if asking that it is for controland the reason/meaning/purpose will be clarified later. As the people gather, most will have a wristband, only in different colors. roomer and gossip does the job.

It is crucially important that the guests are NOT told in advance about the Concept as the idea is, that in a sub-rosian act, and as a tribute to Jane Elliott's Blue Eyes/Brown Eyes Experiment on Racism, the public will be differentiated, told apart and separated into two groups. This idea of sorting, selection, classification and categorizing, a devision mechanism, is put into praxis known well in systems, organizations, and political regimes, but also hints on our natural tendencies towards group dynamics and belonging-not belonging.

colors: 
Silver, Blue, Green.

Groups 
Staff (1%) / a (70%) / b (30%).



text_de:
	
**Teile und Hersche**

"Divide & Rule" ist eine Arbeit über Klassifizierung und Kategorisierung, oder eine Teilung Mechanismus, eine vertraute Praxis Eingesetzt durch verschiedenen Systemen, Organisationen und politischen Regimes. Es deutet auf unsere natürliche Tendenz zur Gruppendynamik und den Begriff der Zugehörigkeit vs. nicht gehörenden. Diese Arbeit ist als eine Hommage an Jane Elliott's "Blue Eyes / Brown Eyes" Rassismus Experiment  bestimmt.
Die Intervention erfolgt im Eingang zum Veranstaltungsort, bei der Eröffnung, wo Besucher und Gäste Eintrittskarten zeigen,  auch beim freien Eintritt am Sicherheitskontrollpunkt. 
Die Künstlerin stellt sich bekleidet (anpassend zur Situation am Eingang), stellt sich neben die für die Sicherheit am Eingang, oder die Ticketverkäufer zuständigen, befragt und bindet den Gästen einem Papier-Armband ein (wie bekannt wenn man zu einem Festival oder ein langes Konzert  geht), und werden ermutigt, es zu tragen. Es gibt drei Farben, so dass die Menschenmenge (Multitude) an diesem Ort in drei Gruppen unterteilt werden:

• Gruppe A - 1 Farbe für die Mehrheit
• Gruppe B -  Die Minderheit, wofür die Streifen in eine andere Farbe und in einer geringeren Menge produziert werden.
• Mitarbeiter - Staff (Selten, für Crew, Mitarbeiter, etc.)

Teilung kann variieren. Allen wird gesagt, wenn gefragt, dass der Grund / Sinn / Zweck der Teilung später geklärt wird*. Da wo die Menschen sich versammeln, haben die meisten dann ein Armband, nur in verschiedenen Farben. Gerüchten und Klatsch wird die Arbeit ausmachen.

Es ist von entscheidender Bedeutung, dass die Gäste nicht im Voraus über das Konzept erzählt werden, die Idee ist, in einem subversivem Akt, (inspiriert von Jane Elliotts "Blue Eyes Brown Eyes" Experiment über Rassismus in der USA in der 60er Jahre), die Kunst des Benehmens in der Öffentlichkeit plötzlich Sichtbar wird,  und dadurch zu Auseinandersetzungen zwischen den Menschen in den zwei Gruppen leitet. Diese Idee der Sortierung, Auswahl, Klassifizierung und Kategorisierung, ein Divisionsmechanismus, wird bekanntlich in der Praxis in Systemen, Organisationen und politischen Regimen eingesetzt, und hier für die Kunst rekrutiert, gilt aber auch an sich als Hinweise auf unsere natürlichen Tendenzen Gruppendynamik und Zugehörigkeit, sowie das streben, nicht dazuzugehören.

*Wenn jemand  am Eingang darauf besteht das zu wissen, kann gesagt werden, es sei für die Sicherheit oder Kontrolle Gründen.



Bisherige Ausführungen: (Seit 2010)
	•	NSK Biennalle Baumwollespinnerei, Leipzig,Germany   
	•	Bauhaus Universität Weimar, Germany
	•	Cacak (Belgrad), Serbia  

	
	
	
	Farben:
 
		•	Silber (Staff)
		•	Grün (Group A)
		•	Blau (Group B)


	Gruppen

		•	Staff  (1% ) 
		•	Group A (69%)  
		•	Group B (30%)
Coll.
konzipiert für die Ich bin was ich bin (I am What I am) Ausstellung Nadežda Petrović Gallery 25. Bienniale, Čačak, Serbia.
+++
