title: Ich Kann Kein Bauhaus Mehr Sehen

title_de: Ich Kann Kein Bauhaus Mehr Sehen

date: 2009

material: 

size: 300 pcs  Edition

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++

Ich Kann Kein Bauhaus Mehr Sehen!

text_de:
+++
