title: "bUrNiNgBlUeSoUl"

title_de: "bUrNiNgBlUeSoUl"

date: 2005

material: Sound & Video installation

size: 15 Stations (Monitores, Headphones, Seats), Projection on screen

1.jpg:
  description: Exhibition view E-Werk, Weimar
  description_de: Ausstellungsansicht, E-Werk, Weimar


content: +++


Sound & Video Installation 

While listening to music, we are entirely on our own, entirely private. But what if we are observed while doing it, placed on display? This installation focuses on just this intersection between private and public. Constantly encircled by the media and market, the private is an endangered category in our society that is threatened with extinction. Interactively crossing between media, this work gives contemporary expression to old "dreams of love." 

Jan Brueggemeier - "bUrNiNgBlUeSoUl" Audio Sequence, .mp3 format 

Coll.
With the friendly support of ZKM Karlsruhe; Agenos GmbH 
Made possible by a special grant of the Federal Commissioner for Cultural and Media Affairs 
Pèlerinages- Kunstfest, E-Werk, Straßenbahndepot, Weimar, Summer 2005. 



text_de:
+++
