title: "Hohenems Firebrigade" 

title_de: "Feuerwehr Hohenems"

date: 2001

material: Videoinstallation, Sound.

size: 

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++
 

The Videoinstallation Firehouse Hohenems refers to the current sitate of the interiors, in which nothing reminds of the original utilization of the Building as a former Synagoge. The surface of the interiors is thrown back upon. This visual doubling make the walls become alive. They seem to become transparent for a glance on the comitted destruction, at the same time refusing new images and answers. With her work, the artist tries to transform the emptiness, that which is missig and cannot be reconstructed into an image of ist own, to offer a reflection surface to the viewer. 


- Four Videobeamer Projections of wall parts 1:1 on same wall parts with Original sound. 

- One Monitor with static Image "You are looking at a Reproduction of a Reproduction" 
(Detail from a reproduction of Paul Klee, Angelus Novus) 

- Art-Indust - "The End" Audio Sequence

http://naomiterezasalmon.net/projects/7-Feuerwehr_Hohenems/feurwehr_hohenems_art_indust_the_end.mp3

text_de:
+++
