title: Life – Terror – Mind

title_de: Leben – Terror – Geist

date: 1999

material: 73 wooden transport crates

size: approx. 90 x 50 x 60 cm each

LTG-Blum.jpg:
  description: Crate of Leon Blum
  description_de: Kiste von Leon Blum

LTG-GNM.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

LTG-Kisten.jpg:
  description: State of depot, Stiftung Weimarer Klassik
  description_de: Fundzustand, Depot, Stiftung Weimarer Klassik


content: +++

This exhibition presents the life and work of seventy-three former inmates - 
representative of many others - who, despite the diversity of their origins, 
their convictions and their life journeys, have one thing in common: 
their imprisonment in Buchenwald Concentration Camp.

In replicas of the wooden crates which inmates of Buchenwald Concentration Camp 
were required to manufacture in 1943 for the safekeeping of valuable archives 
from the centres of German classicism, testimonies to their lives and work are presented: 
manuscripts, photographs, pictures, letters, sound recordings and personal objects.


## Exhibition Stations:

- *1999* — Buchenwald Memorial, Weimar, Germany
- *2000* — Goethe national Museum, Weimar, Germany
- *2003* — Mechelen, Belgium

+++

colophon: +++
The exhibition was developed in cooperation with the Weimar 1999 Kulturstadt Europas GmbH 
and is the result of collaboration between historians and artists.
+++