title: "Schloß E."

title_de: "E. Castle"

date: 2002

material: Rauminstallation, Fotografien, Sound.

size: 

1.jpg:
  description: Exhibition view PCC Gallery, Colone
  description_de: Ausstellungsansicht,PCC Galerie, Köln

2.jpg:
  description: Exhibition view, Goethe National Museum
  description_de: Ausstellungsansicht, Goethe-National-Museum

content: +++



*Dealing with Pückler-Muskau* is the original name of the installation made for the Ettersburg Castle near Weimar, Germany. 

„Unfortunately, I meet in the first steps myself, and as one knows, every double seeing, from squinting and dizziness to double sight, is always a bit apprehensive, well, mind confusing“. (Hermann Fürst von Pückler - Muskau about J. W. Goethe, in Letters of a deceased, 1830-1832) 

- Ground floor: One Monitor linked to a surveilance camera shows the path to the ‚Stern’ 

- Second floor: Window wall covered with photos showing the unseeable landscape, a movement detector activates soundsystem, that re sounds from outside the building 

- Third floor: Two Monitors on the pillar carriers, mirror the images behind themselves, sound: a doubling of the current sounds in the staircase. 

Naomi Tereza Salmon - "Schloss E." Audio Sequence, .mp3 format 

text_de:
+++
